#!/bin/sh
echo "Server: " `uname -a`
echo "OS Version: " `cat /etc/debian_version`
echo "  "
apt -q update
echo "  "
echo "Upgradable packets:"
apt list --upgradable
echo "  "
echo "Storage:"
df -h
echo "  "
echo "Log warnings and errors:"
journalctl -p 4 --since "1 week ago" --no-pager

